name: test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: MatteoH2O1999/setup-rust@v1

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check project
        run: cargo check --all-targets
        shell: bash

      - name: Clippy project
        run: cargo clippy --all-targets
        shell: bash

      - name: Test project
        run: cargo test --all-targets
        shell: bash
